USE [master]
GO

/****** Object:  Database [testDB]    Script Date: 2/22/2022 10:21:25 PM ******/
CREATE DATABASE [testDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\testDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'testDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\testDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [testDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [testDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [testDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [testDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [testDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [testDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [testDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [testDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [testDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [testDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [testDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [testDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [testDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [testDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [testDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [testDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [testDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [testDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [testDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [testDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [testDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [testDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [testDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [testDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [testDB] SET RECOVERY FULL 
GO

ALTER DATABASE [testDB] SET  MULTI_USER 
GO

ALTER DATABASE [testDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [testDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [testDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [testDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [testDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [testDB] SET  READ_WRITE 
GO


USE [testDB]
GO

/****** Object:  Table [dbo].[Price]    Script Date: 2/22/2022 10:21:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Price](
	[ProductId] [int] NOT NULL,
	[Value] [float] NOT NULL
) ON [PRIMARY]

GO

USE [testDB]
GO

/****** Object:  Table [dbo].[Product]    Script Date: 2/22/2022 10:21:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Product](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](100) NOT NULL,
 CONSTRAINT [PK_ProductId] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
